### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by danamestrial** [SuphawitWongfu/VendingMachine#6]
https://github.com/SuphawitWongfu/VendingMachine/blob/a8b1788555a91fad6003b8ec02b97d979197c2ce/app/machine_stocks.py#L20-L24

Even though there is already some encapsulation, it's still not enough and the code is still relatively hard to read. Here's an idea, how about you encapsulate the part where you do validation?

**Comment by SuphawitWongfu** [comment]
Thank you for your idea,  the issue is fixed
