### ISSUE TITLE
No Subdirectories

### ISSUE THREAD

**Issue by danamestrial** [SuphawitWongfu/VendingMachine#7]
https://github.com/SuphawitWongfu/VendingMachine/tree/ae8708535b9d8662fe81c94808ddd1d003b2303a/app

Maybe add more directories in the app folder, something called 'routes' or 'endpoints'. Currently there's like 10 python files in the app folder and it's causing some difficulties to find certain functions.

**Comment by SuphawitWongfu** [comment]
Thank you for you suggestion, the issue is fixed
